help() {
  echo "Available commands:"
  echo "  quit, exit - Exit the script"
  echo "  list       - List files and directories"
  echo "  help       - Display this help message"
  echo "  rm [file]  - Remove a file"
  echo "  rmdir [dir] - Remove an empty directory"
  echo "  about     - Display information about this program"
  echo "  version, --v, vers - Display the version of this prompt"
  echo "  age        - Ask for your age and tell if you're an adult or a minor"
  echo "  profile    - Display profile information from .env"
  echo "  password   - Change your password"
  echo "  cd [dir]   - Change the current directory"
  echo "  pwd        - Print the current working directory"
  echo "  hour       - Print the current hour"
  echo "  Type any other command for it to be recognized as unknown."
  echo "  httpget    - Download the HTML source of a web page and save it to a specific file"
  echo "  open      - Open a file directly in VIM, even if it doesn't exist"
}